vich_uploader:
    db_driver: orm

    mappings:
        user_images:
            uri_prefix: 'C:\xampp\htdocs\victorious-master\public\uploads\images\users'
            upload_destination: 'C:\xampp\htdocs\victorious-master\public\uploads\images\users'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
            #inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        team_images:
            uri_prefix: 'C:\xampp\htdocs\victorious-master\public\uploads\images\teams'
            upload_destination: 'C:\xampp\htdocs\victorious-master\public\uploads\images\teams'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
            #inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

 
             
       
